### PR TITLE
cluster-sync: Use rollout instead of wait

### LINKED ISSUE #61: Change kubectl wait for rollout
**What happened**:
It is safer and cover more corner cases.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by qinqon**
**What this PR does / why we need it**:
Use rollout instead of wait at `make cluster-sync`

**Which issue(s) this PR fixes** 
Fixes #61

```release-note
NONE
```

### CODE REVIEW

File: hack/cluster.sh [hunk 1]
```diff
@@ -74,7 +74,7 @@ function sync() {
     # Generate the manifest with the "sha256" to force kubernetes to reload the image
     sha=$(skopeo inspect --tls-verify=false docker://$img:$tag |jq -r .Digest)
     IMG=$img@$sha make deploy
-    ${KUBECTL} wait -n kubevirt-ipam-controller-system deployment kubevirt-ipam-controller-manager --for condition=Available --timeout 2m
+    ${KUBECTL} rollout status -w -n kubevirt-ipam-controller-system deployment kubevirt-ipam-controller-manager
```
Comment (oshoval) [inline hack/cluster.sh:77]: wdyt about adding `--timeout` please ?

**Review by oshoval — APPROVED** [review]
Thanks

**Comment by oshoval** [comment]
It will solve cases like this one right ?
https://github.com/kubevirt/ipam-extensions/pull/45#issuecomment-2222727917

where there was already deployment, and we cluster-sync a new one
it would wait for the new one to finish loading and the old to be gone iiuc

**Review by maiqueb — APPROVED** [review]

**Comment by oshoval** [comment]
need rebase + /approve please

**Comment by oshoval** [comment]
Fyi please, even with this PR, 2nd cluster-sync does finish even before the old pods terminated 
(same as we had with wait)
It might be ok, but sometimes rare flakes might occur with such behavior, so we might want to tackle it in the future

This is the state of 2nd cluster-sync, after the rollout returned and cluster-sync finished "successfully"

`deployment "kubevirt-ipam-controller-manager" successfully rolled out`

```
kubevirt-ipam-controller-system   kubevirt-ipam-controller-manager-5fdf7fc9f4-blbzz   1/1     Running       0          22s
kubevirt-ipam-controller-system   kubevirt-ipam-controller-manager-66bb5f9b96-mt4w2   1/1     Terminating   0          97m
``
